#include "build.h"
extern "C" {
#include "libavcodec/codec_id.h"
}

enum STREAM_TYPE {
    STREAM_TYPE_NONE
    , STREAM_TYPE_UNKNOWN
    , STREAM_TYPE_MPEG1VIDEO
    , STREAM_TYPE_MPEG2VIDEO
    , STREAM_TYPE_H261
    , STREAM_TYPE_H263
    , STREAM_TYPE_RV
    , STREAM_TYPE_MPEG4
    , STREAM_TYPE_RAWVIDEO
    , STREAM_TYPE_MSMPEG4
    , STREAM_TYPE_WMV
    , STREAM_TYPE_FLV
    , STREAM_TYPE_H264
    , STREAM_TYPE_VP7
    , STREAM_TYPE_VP8
    , STREAM_TYPE_VP9
    , STREAM_TYPE_HEVC
    , STREAM_TYPE_VVC
    , STREAM_TYPE_PCM
    , STREAM_TYPE_ADPCM
    , STREAM_TYPE_MP3
    , STREAM_TYPE_AAC
    , STREAM_TYPE_AC3
    , STREAM_TYPE_DTS
    , STREAM_TYPE_WMA
    , STREAM_TYPE_FLAC
    , STREAM_TYPE_APE
    , STREAM_TYPE_EAC3
    , STREAM_TYPE_OPUS
    , STREAM_TYPE_DVD_SUBTITLE
    , STREAM_TYPE_TEXT
    , STREAM_TYPE_ASS
    , STREAM_TYPE_MOV_TEXT
    , STREAM_TYPE_HDMV_PGS_SUBTITLE
    , STREAM_TYPE_SRT
    , STREAM_TYPE_MICRODVD
    , STREAM_TYPE_WEBVTT
    , STREAM_TYPE_HDMV_TEXT_SUBTITLE
    , STREAM_TYPE_TTML
};

enum MEDIA_TYPE {
    MEDIA_TYPE_UNKNOWN
    , MEDIA_TYPE_VIDEO
    , MEDIA_TYPE_AUDIO
    , MEDIA_TYPE_SUBTITLE
};

STREAM_TYPE avcodecid2streamType(AVCodecID code);
MEDIA_TYPE avmediatype2mediaType(AVMediaType type);
